[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip esp32c6 --log-file probe.txt"
rustflags = [
  "-C", "link-arg=-Tlinkall.x",
  "-C", "link-arg=-Tdefmt.x",
  "-C", "force-frame-pointers",
]

[build]
target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = [ "core" ]
